# Generated by Django 6.0.7 on 2026-07-24 09:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarif',
            options={'ordering': ['-tanggal_mulai', '-created_at'], 'verbose_name': 'Tarif', 'verbose_name_plural': 'Tarif'},
        ),
        migrations.RemoveConstraint(
            model_name='tarif',
            name='unique_tarif_layanan_tanggal',
        ),
        migrations.AddField(
            model_name='tarif',
            name='tanggal_mulai',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Tanggal mulai berlaku'),
        ),
        migrations.AddField(
            model_name='tarif',
            name='tanggal_selesai',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal selesai'),
        ),
        migrations.AlterField(
            model_name='pembayaran',
            name='diverifikasi_oleh',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['administrator', 'kasir']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pembayaran_diverifikasi', to=settings.AUTH_USER_MODEL, verbose_name='Diverifikasi oleh'),
        ),
        migrations.AlterField(
            model_name='tarif',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tarif',
            name='layanan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarif_set', to='administrator.layanan', verbose_name='Layanan'),
        ),
        migrations.AlterField(
            model_name='tarif',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name='tarif',
            name='berlaku_mulai',
        ),
        migrations.RemoveField(
            model_name='tarif',
            name='berlaku_sampai',
        ),
    ]
