# Generated by Django 6.0.7 on 2026-07-24 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_alter_tarif_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kendalalaundry',
            name='ditangani_oleh',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['administrator', 'kasir']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kendala_ditangani', to=settings.AUTH_USER_MODEL, verbose_name='Ditangani oleh'),
        ),
    ]
