# Generated by Django 6.0.4 on 2026-07-26 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_alter_kendalalaundry_ditangani_oleh'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAktivitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('tambah', 'Tambah Data'), ('ubah', 'Ubah Data'), ('hapus', 'Hapus Data'), ('verifikasi', 'Verifikasi'), ('pembayaran', 'Pembayaran'), ('pesanan', 'Pesanan'), ('status', 'Perubahan Status'), ('lainnya', 'Lainnya')], default='lainnya', max_length=20, verbose_name='Jenis Aktivitas')),
                ('aktivitas', models.CharField(max_length=255, verbose_name='Aktivitas')),
                ('objek', models.CharField(blank=True, max_length=150, verbose_name='Objek/Data')),
                ('keterangan', models.TextField(blank=True, verbose_name='Keterangan')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Alamat IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='Perangkat')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Aktivitas')),
                ('pengguna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_aktivitas', to=settings.AUTH_USER_MODEL, verbose_name='Pengguna')),
            ],
            options={
                'verbose_name': 'Log Aktivitas',
                'verbose_name_plural': 'Log Aktivitas',
                'ordering': ['-dibuat_pada'],
            },
        ),
    ]
