# Generated by Django 6.0.4 on 2026-07-26 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_logaktivitas'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notifikasi',
            name='administrat_penerim_fb8690_idx',
        ),
        migrations.AddField(
            model_name='notifikasi',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Sudah Dibaca'),
        ),
        migrations.AddField(
            model_name='notifikasi',
            name='link',
            field=models.CharField(blank=True, max_length=255, verbose_name='Tautan'),
        ),
        migrations.AlterField(
            model_name='notifikasi',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Dibuat Pada'),
        ),
        migrations.AlterField(
            model_name='notifikasi',
            name='jenis',
            field=models.CharField(choices=[('info', 'Informasi'), ('pesanan', 'Pesanan'), ('pembayaran', 'Pembayaran'), ('status', 'Perubahan Status'), ('verifikasi', 'Verifikasi'), ('kendala', 'Kendala'), ('penugasan', 'Penugasan')], default='info', max_length=20, verbose_name='Jenis Notifikasi'),
        ),
        migrations.RemoveField(
            model_name='notifikasi',
            name='dibaca_pada',
        ),
        migrations.RemoveField(
            model_name='notifikasi',
            name='pesanan',
        ),
        migrations.RemoveField(
            model_name='notifikasi',
            name='sudah_dibaca',
        ),
        migrations.RemoveField(
            model_name='notifikasi',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='notifikasi',
            name='url',
        ),
    ]
