# Generated by Django 6.0.7 on 2026-07-26 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_remove_notifikasi_administrat_penerim_fb8690_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingUlasan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.PositiveSmallIntegerField(choices=[(1, '1 Bintang'), (2, '2 Bintang'), (3, '3 Bintang'), (4, '4 Bintang'), (5, '5 Bintang')], verbose_name='Rating')),
                ('ulasan', models.TextField(blank=True, verbose_name='Ulasan')),
                ('balasan_admin', models.TextField(blank=True, verbose_name='Balasan Administrator')),
                ('is_tampil', models.BooleanField(default=True, verbose_name='Tampilkan Ulasan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_ulasan', to=settings.AUTH_USER_MODEL, verbose_name='Pelanggan')),
                ('pesanan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating_ulasan', to='administrator.pesanan', verbose_name='Pesanan')),
            ],
            options={
                'verbose_name': 'Rating dan Ulasan',
                'verbose_name_plural': 'Rating dan Ulasan',
                'ordering': ['-created_at'],
            },
        ),
    ]
