# Generated by Django 6.0.4 on 2026-07-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_ratingulasan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=True, help_text='Akun pelanggan langsung aktif setelah registrasi.', verbose_name='Terverifikasi'),
        ),
    ]
