# Generated by Django 6.0.4 on 2026-07-27 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0007_alter_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesanan',
            name='cara_barang_keluar',
            field=models.CharField(choices=[('diambil_sendiri', 'Diambil Sendiri di Outlet'), ('diantar_ke_pelanggan', 'Diantar ke Alamat Pelanggan')], db_index=True, default='diambil_sendiri', max_length=30, verbose_name='Cara barang dikembalikan'),
        ),
        migrations.AddField(
            model_name='pesanan',
            name='cara_barang_masuk',
            field=models.CharField(choices=[('diantar_ke_outlet', 'Diantar ke Outlet'), ('dijemput', 'Dijemput ke Alamat Pelanggan')], db_index=True, default='diantar_ke_outlet', max_length=30, verbose_name='Cara barang masuk'),
        ),
        migrations.AlterField(
            model_name='pesanan',
            name='status',
            field=models.CharField(choices=[('menunggu_barang_diantar', 'Menunggu Barang Diantar'), ('menunggu_penjemputan', 'Menunggu Penjemputan'), ('menunggu_pemeriksaan', 'Menunggu Pemeriksaan'), ('menunggu_petugas', 'Menunggu Petugas Tersedia'), ('menunggu_antrian', 'Menunggu Antrian'), ('dicuci', 'Dicuci'), ('dikeringkan', 'Dikeringkan'), ('disetrika', 'Disetrika'), ('dilipat', 'Dilipat'), ('dikemas', 'Dikemas'), ('siap_diambil', 'Siap Diambil'), ('siap_diantar', 'Siap Diantar'), ('dalam_pengantaran', 'Dalam Pengantaran'), ('selesai', 'Selesai'), ('ditolak', 'Ditolak'), ('dibatalkan', 'Dibatalkan')], db_index=True, default='menunggu_barang_diantar', max_length=30, verbose_name='Status pesanan'),
        ),
        migrations.AlterField(
            model_name='riwayatstatus',
            name='status_baru',
            field=models.CharField(choices=[('menunggu_barang_diantar', 'Menunggu Barang Diantar'), ('menunggu_penjemputan', 'Menunggu Penjemputan'), ('menunggu_pemeriksaan', 'Menunggu Pemeriksaan'), ('menunggu_petugas', 'Menunggu Petugas Tersedia'), ('menunggu_antrian', 'Menunggu Antrian'), ('dicuci', 'Dicuci'), ('dikeringkan', 'Dikeringkan'), ('disetrika', 'Disetrika'), ('dilipat', 'Dilipat'), ('dikemas', 'Dikemas'), ('siap_diambil', 'Siap Diambil'), ('siap_diantar', 'Siap Diantar'), ('dalam_pengantaran', 'Dalam Pengantaran'), ('selesai', 'Selesai'), ('ditolak', 'Ditolak'), ('dibatalkan', 'Dibatalkan')], max_length=30, verbose_name='Status baru'),
        ),
        migrations.AlterField(
            model_name='riwayatstatus',
            name='status_sebelumnya',
            field=models.CharField(blank=True, choices=[('menunggu_barang_diantar', 'Menunggu Barang Diantar'), ('menunggu_penjemputan', 'Menunggu Penjemputan'), ('menunggu_pemeriksaan', 'Menunggu Pemeriksaan'), ('menunggu_petugas', 'Menunggu Petugas Tersedia'), ('menunggu_antrian', 'Menunggu Antrian'), ('dicuci', 'Dicuci'), ('dikeringkan', 'Dikeringkan'), ('disetrika', 'Disetrika'), ('dilipat', 'Dilipat'), ('dikemas', 'Dikemas'), ('siap_diambil', 'Siap Diambil'), ('siap_diantar', 'Siap Diantar'), ('dalam_pengantaran', 'Dalam Pengantaran'), ('selesai', 'Selesai'), ('ditolak', 'Ditolak'), ('dibatalkan', 'Dibatalkan')], max_length=30, verbose_name='Status sebelumnya'),
        ),
    ]
