# Generated by Django 6.0.4 on 2026-07-27 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0008_pesanan_cara_barang_keluar_pesanan_cara_barang_masuk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JenisBarang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dibuat pada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Diubah pada')),
                ('nama', models.CharField(max_length=100, unique=True, verbose_name='Nama jenis barang')),
                ('deskripsi', models.TextField(blank=True, verbose_name='Deskripsi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Jenis Barang',
                'verbose_name_plural': 'Jenis Barang',
                'ordering': ['nama'],
            },
        ),
        migrations.AddField(
            model_name='detailpesanan',
            name='jenis_barang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detail_pesanan', to='administrator.jenisbarang', verbose_name='Jenis barang'),
        ),
    ]
