# Generated by Django 6.0.4 on 2026-07-27 12:02

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0009_jenisbarang_detailpesanan_jenis_barang'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailpesanan',
            name='berat_aktual',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Berat hasil penimbangan oleh kasir dalam kilogram.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Berat aktual'),
        ),
        migrations.AddField(
            model_name='detailpesanan',
            name='harga_final',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Harga akhir yang ditentukan kasir setelah pemeriksaan.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Harga final'),
        ),
        migrations.AddField(
            model_name='detailpesanan',
            name='jumlah_barang',
            field=models.PositiveIntegerField(default=1, help_text='Jumlah item yang diisi pelanggan saat membuat pesanan.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Jumlah barang'),
        ),
    ]
